spring:
  application:
    name: iot-interface
  boot:
    admin:
      client:
        url: http://localhost:8179
  redis:
    host: localhost
    port: 6379
    database: 0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: device
  rabbitmq:
    device:
      addresses: localhost
      port: 5672
      username: admin 
      password: admin 
    ocean:
      addresses: localhost
      port: 5672
      username: admin 
      password: admin 
    waste:
      addresses: localhost
      port: 5672
      username: admin 
      password: admin 
      virtualhost: js-waste

mqtt:
  server:
    url: tcp://localhost:1883
  client:
    id: beida_mqtt_client_demo
    random: true
  userName: admin1
  password: public

lanyun:
  device:
    blackKey: black_list
    wastedevicekey: wasteCollectDevice
  service:
    device:
      host: http://localhost
      port: 8183
    ocean:
      host: http://localhost
      port: 8182
    waste:
      host: http://wfsjapi.tian-wang.com
      port:

logging:
  level: 
    com.lanyun.datasource: debug
  file: iot-interface.log

cloud:
  gateway:
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8077/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS