spring:
  redis:
    host: r-2ze3fa9fbcd4d544pd.redis.rds.aliyuncs.com
    port: 26379
    password: Tiangwang20190220+*-@$
    database: 9
  data:
    mongodb:
      host: 47.94.232.190
      password: Rainbow-lanjing
      username: lanjingdev
      port: 27017
      database: device
  rabbitmq:
    haiyou1:
      username: guest
      password: guest
      port: 5672
      host: 47.94.232.190
    haiyou2:
      username: guest
      password: guest
      port: 5672
      host: 47.94.232.190
      virtual-host: haiyou-2.0

mqtt:
  server:
    url: tcp://47.94.232.190:1883
  client:
    id: irainbow_mqtt_client_789
    random: true
  userName: admin
  password: public

lanyun:
  device:
    blackKey: black_list
  service:
    device:
      host: http://devdevice.tian-wang.com
      port:
